services:
  meilisearch:
    image: getmeili/meilisearch:v0.28.1
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/meili_data
    environment:
      MEILI_MASTER_KEY: 'meiliKey'
  redis:
    image: redis:6.2.6
    restart: unless-stopped
  paktum_server:
    image: privateger/paktum:master
    restart: unless-stopped
    volumes:
      - "images:/home/paktum/images/"
    depends_on:
      - redis
      - meilisearch
    ports:
      - 8080:8080
    command:
      - "--mode=server"
      - "--redis=redis:6379"
      - "--meilihost=http://meilisearch:7700"
      - "--meilikey=meiliKey"
      - "--imageDir=/home/paktum/images/"
  image_processor:
    image: privateger/paktum:master
    restart: unless-stopped
    volumes:
      - "images:/home/paktum/images/"
    depends_on:
      - redis
      - meilisearch
    command:
      - "--mode=process"
      - "--redis=redis:6379"
      - "--meilihost=http://meilisearch:7700"
      - "--meilikey=meiliKey"
      - "--imageDir=/home/paktum/images/"
  image_scraper:
    image: privateger/paktum:master
    restart: "no"
    depends_on:
      - redis
    command:
      - "--mode=scrape"
      - "--redis=redis:6379"
    profiles:
      - donotstart
  image_cleanup:
    image: privateger/paktum:master
    restart: "no"
    depends_on:
      - meilisearch
    environment:
      - "LOG_LEVEL=DEBUG"
    command:
      - "--mode=cleanup"
      - "--meilihost=http://meilisearch:7700"
      - "--redis=redis:6379"
      - "--meilikey=meiliKey"
    profiles:
      - donotstart

volumes:
    images:
    meilisearch-data:
